teamforus/forus-frontend-react

react/src/dashboard/components/pages/implementations-view/ImplementationsView.tsx
=> Set permissions for fund actions on implementation page

.github/dependabot.yml, .github/workflows/auto_pr_on_master_push.yml, .github/workflows/compile_and_build.yml
- Added monthly upgrades for dependencies versions with assignees on @dev-rminds and @lexlog 
- Added PR creation for master/develop diff after release
- Changed compiling list in CI to webshop general and dasboards
=> ci updates

env.example.js, react/public/index.ejs, webpack.config.js
=> add default page title to env

react/src/dashboard/components/elements/table-empty-value/TableEmptyValue.tsx, react/src/dashboard/components/pages/employees/Employees.tsx, react/src/dashboard/components/pages/financial-dashboard-overview/elements/FinancialOverviewFundsTable.tsx, react/src/dashboard/components/pages/organizations-funds-edit/OrganizationsFundsEdit.tsx, react/src/dashboard/components/pages/transaction-bulks-view/TransactionBulksView.tsx, react/src/dashboard/components/pages/vouchers-view/VouchersViewComponent.tsx, react/src/dashboard/hooks/usePushApiError.tsx
- fix: white screen on statistics overview when you have funds without budget
- fix: fund is created without a picture though the picture was added at creation
- Start bulk payment keep button disabled and icon spinning until the redirect is finished
- hide delete button for owner on employees list
- show push error when trying to access a voucher while not having access
=> sponsor dashboard fixes

react/src/dashboard/components/elements/block-reimbursement-categories/BlockReimbursementCategories.tsx, react/src/dashboard/components/modals/ModalEmployeeEdit.tsx, react/src/dashboard/components/pages/employees/Employees.tsx, react/src/dashboard/components/pages/organizations-edit/elements/OrganizationForm.tsx, react/src/dashboard/components/pages/pre-check/PreCheck.tsx, react/src/dashboard/components/pages/provider-funds/elements/ProviderAvailableFundsTable.tsx, react/src/dashboard/components/pages/provider-funds/elements/ProviderFundInvitationsTable.tsx, react/src/dashboard/components/pages/provider-funds/elements/ProviderFundUnsubscriptionsTable.tsx, react/src/dashboard/components/pages/provider-funds/elements/ProviderFundsTable.tsx, react/src/dashboard/components/pages/sponsor-provider-organizations/elements/ProvidersTableItemFunds.tsx, react/src/dashboard/components/pages/transactions-view/elements/TransactionDetails.tsx, react/src/dashboard/components/pages/vouchers/ProductVouchers.tsx, react/src/dashboard/components/pages/vouchers/elements/VouchersTableHeader.tsx, react/src/dashboard/components/pages/vouchers/elements/VouchersTableRow.tsx, react/src/dashboard/hooks/useIsProviderPanel.tsx
- white screen when open screen vouchers page while having a voucher from a fund which is not configured (edge case)
- not possible to create a voucher while having a not configured fund
- remove visual required from btw-number field
- fix infinite loading for transaction details on declaration details page
- fix declaration categories table not being updated after a category was remove without a page reload
- remove branch details from employees page from sponsor and validator panels
- update list of buttons on markdown editor from organization edit page
- WCAG requirements are met - new feature is accessible by …
=> fixes for release 118: sponsor dashboard

react/src/dashboard/components/modals/ModalExportDataSelect.tsx, react/src/dashboard/components/modals/ModalSwitchBankConnectionAccount.tsx, react/src/dashboard/components/modals/ModalVoucherTransaction/ModalVoucherTransaction.tsx, react/src/dashboard/components/modals/ModalVoucherTransaction/ModalVoucherTransactionPreview.tsx, react/src/dashboard/components/pages/sponsor-provider-organization/elements/FundProviderTableItem.tsx, react/src/dashboard/components/pages/sponsor-provider-organization/elements/ProviderOrganizationOverview.tsx, react/src/dashboard/components/pages/sponsor-provider-organization/hooks/useConfirmAcceptBudgetFundProvider.tsx, react/src/dashboard/components/pages/transactions-view/elements/TransactionDetails.tsx
- disable submit button for create voucher transaction modal while the amount is 0
- fix loading state on approve provider button not being reseted when modal is closed without approval leading to infinite loading state.
- bank connection page fix modal not being closed after the modal/form is submitted.
- fix error keys on create voucher transaction modal leading to error from provider field being shown under the amount and note field as well.
- fix incorrect view voucher url on transaction details page,
=> fixes for release 118: part 3

react/src/dashboard/components/modals/ModalVoucherTransaction/ModalVoucherTransaction.tsx, react/src/dashboard/components/modals/ModalVoucherTransaction/ModalVoucherTransactionPreview.tsx, react/src/dashboard/hooks/useActiveOrganization.tsx
- fixed transactions modal amount field, not being able to add leading 0 to decimal values
- fixed opening urls on panels where organizationId is not the same as the active one
=> release 118 fixes: part 4

react/src/dashboard/hooks/useActiveOrganization.tsx
=> fix useActiveOrganization organization update in some cases

react/assets/forus-webshop/scss/_common/components/_form.scss, react/src/dashboard/components/elements/select-control/templates/SelectControlOptions.tsx
=> remove extra border from select-controls on webshops

react/src/webshop/components/pages/products-show/ProductsShow.tsx, react/src/webshop/components/pages/products-show/elements/ProductFundsCard.tsx
=> Show product page when funds loaded for reservation block

react/src/webshop/components/elements/lists/funds-list/FundsListItem.tsx, react/src/webshop/components/elements/lists/funds-list/templates/FundsListItemList.tsx
=> Change the fund item block to become clickable

custom.d.ts, package-lock.json, package.json, react/src/dashboard/services/MarkdownService.ts
=> Fix summernote tables format for markdown conversion

react/assets/forus-platform/scss/_common/includes/common.scss, react/src/dashboard/components/pages/csv_validations/elements/CSVUpload.tsx, react/src/dashboard/components/pages/fund_requests-view/FundRequestsView.tsx, react/src/dashboard/i18n/i18n-nl.js, react/src/webshop/components/pages/vouchers-show/VouchersShow.tsx
=> fix formatation and panel paginator text

.github/workflows/compile_and_build.yml
=> up node on CI building

react/src/webshop/components/modals/modal-product-reserve/ModalProductReserve.tsx
=> Fix date format in product reservation form

react/public/index.ejs
=> Replace Zoho Desk chat with Zendesk

react/src/webshop/components/elements/cms-blocks/CmsBlocks.tsx
=> Fix link target in cms block

react/assets/forus-webshop/scss/vergoedingen/includes/shame.scss, react/src/webshop/components/elements/top-navbar/TopNavbar.tsx, react/src/webshop/components/elements/top-navbar/TopNavbarSearch.tsx
=> fix the hover effect of Vergoedingen navbar search button

env.example.js, package-lock.json, package.json, react/public/index.ejs, react/src/props/EnvDataWebshopProp.ts, react/src/website/Website.tsx, react/src/website/modules/google_tag_manager/GoogleTagManager.tsx
=> add Google Tag Manager to the website

react/src/dashboard/components/modals/ModalReservationCreate.tsx, react/src/dashboard/components/pages/identitities-show/elements/IdentityVouchersCard.tsx, react/src/dashboard/components/pages/identity-security/Security2FA.tsx, react/src/dashboard/components/pages/implementations-notifications-send/ImplementationsNotificationsSend.tsx, react/src/dashboard/components/pages/organizations-funds-show/elements/OrganizationsFundsShowIdentitiesCard.tsx, react/src/dashboard/components/pages/transactions-view/elements/TransactionDetails.tsx, react/src/dashboard/components/pages/vouchers-view/VouchersViewComponent.tsx, react/src/dashboard/i18n/en/modals/modal-voucher-create.js, react/src/dashboard/i18n/en/modals/modal-voucher-qr_code.js, react/src/dashboard/i18n/en/pages/vouchers.js, react/src/dashboard/i18n/i18n-nl.js, react/src/dashboard/i18n/nl/pages/reimbursements.js, react/src/dashboard/i18n/nl/pages/vouchers.js
=> Rename vouchers to tegoeden

react/assets/forus-webshop/scss/_common/sections/blocks/block-navbar-search.scss, react/assets/forus-webshop/scss/doetegoed/sections/blocks/block-navbar-search.scss, react/assets/forus-webshop/scss/doetegoed/sections/blocks/block-navbar.scss, react/assets/forus-webshop/scss/eemsdelta/sections/blocks/block-navbar-search.scss, react/assets/forus-webshop/scss/eemsdelta/sections/blocks/block-navbar.scss, react/assets/forus-webshop/scss/groningen/sections/blocks/block-navbar-search.scss, react/assets/forus-webshop/scss/groningen/sections/blocks/block-navbar.scss, react/assets/forus-webshop/scss/style-webshop-doetegoed.scss, react/assets/forus-webshop/scss/style-webshop-eemsdelta.scss, react/assets/forus-webshop/scss/style-webshop-groningen.scss, react/assets/forus-webshop/scss/vergoedingen/includes/shame.scss, react/src/webshop/components/elements/top-navbar/TopNavbarSearch.tsx, react/src/webshop/components/pages/funds-pre-check/FundsPreCheck.tsx, react/src/webshop/components/pages/funds/Funds.tsx, react/src/webshop/components/pages/providers/Providers.tsx, react/src/webshop/components/pages/reservations/Reservations.tsx, react/src/webshop/i18n/i18n-nl.js, react/src/webshop/i18n/nl/pages/funds.js, react/src/webshop/i18n/nl/pages/providers.js, react/src/webshop/i18n/nl/pages/reservations.js
=> Add label for search input on webshop

react/assets/forus-webshop/scss/_common/sections/blocks/block-fund.scss, react/assets/forus-webshop/scss/potjeswijzer/includes/shame.scss, react/assets/forus-webshop/scss/schagen/includes/shame.scss, react/assets/forus-webshop/scss/vergoedingen/includes/shame.scss, react/src/webshop/components/pages/funds-show/FundsShow.tsx
=> update fund details page design

react/src/webshop/components/pages/products/Products.tsx, react/src/webshop/components/pages/providers/Providers.tsx
=> fix action fund filters on webshop

react/src/dashboard/components/elements/forms/controls/PhoneControl.tsx, react/src/webshop/components/elements/select-control/templates/SelectControlOptionsVouchers.tsx, react/src/webshop/components/modals/Modal2FASetup.tsx, react/src/webshop/components/modals/ModalDeactivateVoucher.tsx, react/src/webshop/components/modals/ModalOpenInMe.tsx, react/src/webshop/components/modals/ModalPhysicalCardType.tsx, react/src/webshop/components/modals/ModalShareVoucher.tsx, react/src/webshop/components/modals/modal-product-reserve/ModalProductReserve.tsx, react/src/webshop/components/pages/auth/Start.tsx, react/src/webshop/components/pages/bookmarked-products/BookmarkedProducts.tsx, react/src/webshop/components/pages/fund-requests-show/elements/FundRequestRecordClarificationCard.tsx, react/src/webshop/components/pages/fund-requests/FundRequests.tsx, react/src/webshop/components/pages/funds-pre-check/FundsPreCheck.tsx, react/src/webshop/components/pages/funds-request/elements/steps/FundRequestStepContactInformation.tsx, react/src/webshop/components/pages/funds-request/elements/steps/FundRequestStepCriteria.tsx, react/src/webshop/components/pages/funds-request/elements/steps/FundRequestStepEmailSetup.tsx, react/src/webshop/components/pages/funds/Funds.tsx, react/src/webshop/components/pages/identity-emails/PreferencesEmails.tsx, react/src/webshop/components/pages/products/Products.tsx, react/src/webshop/components/pages/providers/Providers.tsx, react/src/webshop/components/pages/reimbursements-edit/ReimbursementsEdit.tsx, react/src/webshop/components/pages/reimbursements/Reimbursements.tsx, react/src/webshop/components/pages/reservations/Reservations.tsx, react/src/webshop/components/pages/search/Search.tsx
I made a small translation for phone-control from "Enter phone number" to "Voer telefoonnummer in", perhaps a better translation is needed.
Add tag if PR:
=> wcag: remove input placeholders on webshops

react/src/webshop/components/pages/funds-activate/FundActivate.tsx, react/src/webshop/components/pages/funds-pre-check/FundsPreCheck.tsx, react/src/webshop/components/pages/funds-request/elements/steps/FundRequestStepCriteria.tsx
- restore placeholders for fund-application and pre-check select-controls
- fix fund-request already exists screen in some cases
=> release 124 fixes

react/src/webshop/components/pages/auth/Start.tsx, react/src/webshop/i18n/nl/pages/signup.js
=> Remove wcag suffix from login webshop

react/src/webshop/i18n/nl/pages/home.js
=> fix incorrect implementation auth button text

react/src/webshop/components/elements/top-navbar/TopNavbar.tsx
=> Make logo not clickable for home page on webshop

react/src/webshop/components/elements/lists/funds-list/templates/FundsListItemList.tsx, react/src/webshop/components/elements/top-navbar/TopNavbarSearch.tsx, react/src/webshop/i18n/i18n-nl.js, react/src/webshop/i18n/nl/pages/funds.js
- removed alt text for funds images
- changed all funds titles, breadcrumbs and tab name for Nijmegen and Overflakkee according to their custom menu page names
- changed type of general search bar input
=> WCAG minor fixes

react/src/dashboard/components/elements/forms/ui-controls/UIControlDate.tsx, react/src/dashboard/components/elements/forms/ui-controls/UIControlNumber.tsx, react/src/dashboard/components/elements/forms/ui-controls/UIControlStep.tsx, react/src/dashboard/components/elements/forms/ui-controls/UIControlText.tsx, react/src/dashboard/components/elements/select-control/templates/SelectControlOptions.tsx, react/src/dashboard/components/elements/select-control/templates/SelectControlOptionsCountryCodes.tsx, react/src/dashboard/components/elements/select-control/templates/SelectControlOptionsFund.tsx, react/src/webshop/components/elements/lists/products-list/templates/ProductsListItemGrid.tsx, react/src/webshop/components/elements/lists/products-list/templates/ProductsListItemList.tsx, react/src/webshop/components/elements/select-control/templates/SelectControlOptionsVouchers.tsx, react/src/webshop/components/elements/top-navbar/TopNavbar.tsx, react/src/webshop/components/pages/identity-emails/PreferencesEmails.tsx, react/src/webshop/components/pages/products-show/ProductsShow.tsx, react/src/webshop/components/pages/products/Products.tsx, react/src/webshop/components/pages/providers/Providers.tsx, react/src/webshop/layout/elements/LayoutMobileMenu.tsx
added aria labels translations
=> aria labels translations

react/assets/forus-platform/scss/_common/blocks/block-markdown.scss, react/assets/forus-webshop/scss/_common/sections/blocks/block-cms.scss, react/assets/forus-webshop/scss/_common/sections/blocks/block-markdown.scss, react/assets/forus-webshop/scss/_common/sections/blocks/block-showcase.scss, react/src/webshop/components/elements/block-showcase/BlockShowcasePage.tsx, react/src/webshop/components/elements/markdown/Markdown.tsx, react/src/webshop/components/elements/top-navbar/TopNavbar.tsx, react/src/webshop/components/pages/products/Products.tsx, react/src/webshop/i18n/nl/layout/navbar.js
=> WCAG filter enhancement on mobile, add table scrollable

react/assets/forus-webshop/scss/_common/components/_buttons.scss, react/assets/forus-webshop/scss/_common/sections/blocks/voucher.scss, react/assets/forus-webshop/scss/style-webshop-berkelland-vars.scss, react/assets/forus-webshop/scss/style-webshop-doetegoed-vars.scss, react/assets/forus-webshop/scss/style-webshop-ede-vars.scss, react/assets/forus-webshop/scss/style-webshop-eemsdelta-vars.scss, react/assets/forus-webshop/scss/style-webshop-geertruidenberg-vars.scss, react/assets/forus-webshop/scss/style-webshop-general-vars.scss, react/assets/forus-webshop/scss/style-webshop-goereeoverflakkee-vars.scss, react/assets/forus-webshop/scss/style-webshop-groningen-vars.scss, react/assets/forus-webshop/scss/style-webshop-hartvanwestbrabant-vars.scss, react/assets/forus-webshop/scss/style-webshop-heumen-vars.scss, react/assets/forus-webshop/scss/style-webshop-kerstpakket-vars.scss, react/assets/forus-webshop/scss/style-webshop-noordoostpolder-vars.scss, react/assets/forus-webshop/scss/style-webshop-oostgelre-vars.scss, react/assets/forus-webshop/scss/style-webshop-potjeswijzer-vars.scss, react/assets/forus-webshop/scss/style-webshop-schagen-vars.scss, react/assets/forus-webshop/scss/style-webshop-vergoedingen-vars.scss, react/assets/forus-webshop/scss/style-webshop-waalwijk-vars.scss, react/assets/forus-webshop/scss/style-webshop-winterswijk-vars.scss, react/assets/forus-webshop/scss/vergoedingen/includes/shame.scss
=> remove uppercase for nijmegen

react/src/dashboard/components/pages/vouchers/Vouchers.tsx
=> Hide voucher amount in table if no budget funds

react/src/dashboard/components/elements/block-card-emails/BlockCardEmails.tsx
=> translation email messages in validator dashboard

react/src/webshop/components/pages/funds-request/elements/steps/FundRequestStepEmailSetup.tsx
=> Fix missing email sent block in fund request webshop

.eslintrc.js, package-lock.json, package.json, react/src/dashboard/components/elements/select-control/templates/SelectControlOptions.tsx, react/src/dashboard/components/elements/select-control/templates/SelectControlOptionsCountryCodes.tsx, react/src/dashboard/components/modals/ModalDuplicatesPicker.tsx, react/src/dashboard/components/modals/ModalFundProviderChatProvider.tsx, react/src/dashboard/components/modals/ModalFundProviderChatSponsor.tsx, react/src/dashboard/components/pages/fund-provider/FundProvider.tsx, react/src/dashboard/components/pages/pre-check/PreCheck.tsx, react/src/dashboard/components/pages/provider-funds/elements/ProviderFundInvitationsTable.tsx, react/src/dashboard/components/pages/sponsor-provider-organization/SponsorProviderOrganization.tsx, react/src/dashboard/components/pages/sponsor-provider-organizations/SponsorProviderOrganizations.tsx, react/src/dashboard/helpers/ProgressStorage.ts, react/src/dashboard/hooks/useFilter.tsx, react/src/dashboard/modules/filter_next/useFilterNext.tsx, react/src/webshop/components/elements/select-control/templates/SelectControlOptionsVouchers.tsx, react/src/webshop/components/pages/cms-pages/Accessibility.tsx, react/src/webshop/components/pages/funds-request/FundRequest.tsx
@dev-rminds due to conflicts in original PR i recreated it from develop and added [your changes](https://github.com/teamforus/forus-frontend-react/pull/249/commits/2ab7f14976a60c22641062d38cf4b399e7ff8c04) +
- [regenerated package-lock.json](https://github.com/teamforus/forus-frontend-react/pull/249/commits/f4eda527a6d0a31a428dd2f7abae91c687c5e730) fully to fix conflicts and renew file
- [fixed new linter errors](https://github.com/teamforus/forus-frontend-react/pull/249/commits/80b75dd7834115d37381fd5058acafc3a4086c8a)
- …
=> bump prettier and regenerate package-lock.json from develop
